language: swift
osx_image: xcode8.3
script:
  - xcodebuild -scheme InstantMock-Example -workspace Example/InstantMock.xcworkspace  -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'InstantMock'
